### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Triangle-Ops** [Triangle-Ops/Triangle-Ops#1]
![Banner](https://user-images.githubusercontent.com/105134343/172748127-35ae40c5-d8da-4bca-b03e-6934d8eedd49.png)
![social-media-banner](https://user-images.githubusercontent.com/105134343/172748954-eea2e2a5-ac79-419b-bdee-3bc105ec3e07.png)

**Comment by kristlyuen** [comment]
@rachelschipull I'm closing this one out. You can still access it if you need the image links!
